# Generated by Django 4.1 on 2022-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="name",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="url",
        ),
        migrations.AddField(
            model_name="resource",
            name="slug",
            field=models.SlugField(
                default="djangodbmodelsfieldscharfield", max_length=60, unique=True
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="title",
            field=models.CharField(default="test", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(unique=True, upload_to="../../../resources/files"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="image",
            field=models.ImageField(unique=True, upload_to="../../../resources/images"),
        ),
    ]
