# Generated by Django 4.1 on 2022-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_resource_name_remove_resource_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                unique=True,
                upload_to="C:UserschcalOneDriveDocumentsGitHubeducational-resources-technology-hub\\resourcesfiles",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                upload_to="C:UserschcalOneDriveDocumentsGitHubeducational-resources-technology-hub\\resourcesimages"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="slug",
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
