# Generated by Django 4.1 on 2022-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_resource_file_alter_resource_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                max_length=200,
                unique=True,
                upload_to="C:/Users/chcal/OneDrive/Documents/GitHub/educational-resources-technology-hub/resources/files/",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                upload_to="C:/Users/chcal/OneDrive/Documents/GitHub/educational-resources-technology-hub/resources/images/"
            ),
        ),
    ]
