# Generated by Django 4.1 on 2022-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_resource_file_alter_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(max_length=200, upload_to='C:/Users/chcal/OneDrive/Documents/GitHub/educational-resources-technology-hub/educational_resources_technology/home/static/images/resources/'),
        ),
    ]
