# Generated by Django 4.1 on 2022-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_ssid_wifi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(max_length=200, unique=True, upload_to='C:/Users/chcal/OneDrive/Documents/GitHub/educational-resources-technology-hub/resources/files/'),
        ),
    ]
