# Generated by Django 4.1 on 2022-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(max_length=200, unique=True, upload_to='resources/files/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(max_length=200, upload_to='educational_resources_technology/home/static/images/resources/'),
        ),
    ]
