# Generated by Django 4.1 on 2022-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_resource_file_alter_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(max_length=200, upload_to='home/static/images/resources/'),
        ),
    ]
