# Generated by Django 4.1.7 on 2023-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_alter_resource_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="file",
        ),
        migrations.AlterField(
            model_name="resource",
            name="slug",
            field=models.URLField(max_length=100, unique=True),
        ),
    ]
