# Generated by Django 4.1.7 on 2023-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_remove_resource_file_alter_resource_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(
                default="testfile", max_length=200, upload_to="resources/files/"
            ),
            preserve_default=False,
        ),
    ]
