# Generated by Django 4.1.7 on 2023-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_resource_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
