version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./educational_resources_technology:/educational_resources_technology
    environment:
      - SECRET_KEY=django-insecure-l^zerl=#@h@a2@1#j^&ki-o8z#^jw1j3ih)7qkxcj5p^@c(1u9
      - DEBUG=1
      - DB_HOST=db
      - DB_NAmE=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
    depends_on:
      - db
      - kiwix
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
