version: '3.9'

services:
  app:
    build:
      context: ./educational_resources_technology
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: bash -c "python educational_resources_technology/manage.py makemigrations && python educational_resources_technology/manage.py migrate && python educational_resources_technology/manage.py runserver 0.0.0.0:8000"
