services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    volumes:
      - ./resources:/app/resources
    networks:
      - app-network

  kiwix:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0
    ports:
      - "8080:8080"
    volumes:
      - ./zim:/data
    command: '*.zim'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 